import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { AuthProvider } from "@/lib/auth/authContext";
import { NotificationProvider } from "@/contexts/NotificationContext";
import { Toaster } from "@/components/ui/sonner";
import { RouteTransition } from "@/components/system/RouteTransition";
import { NotificationToastProvider } from '@/components/NotificationToast';




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light" suppressHydrationWarning>
      <head>
          <link
          href="https://api.mapbox.com/mapbox-gl-js/v2.15.0/mapbox-gl.css"
          rel="stylesheet"
        />
      </head>
     
      {/* <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}> */}
      <body className={` antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange // Prevent flickering during theme changes
        >
            <AuthProvider>
              <NotificationProvider>
                <NotificationToastProvider>
                  <RouteTransition>
                  {children}
                  </RouteTransition>
                  <Toaster />
                </NotificationToastProvider>
              </NotificationProvider>
            </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}